image: r-base

pages:
  stage: deploy
  script:
    - R -e 'options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/latest"))'
    - R -e 'install.packages("pkgdown")'
    - R -e 'pkgdown::build_site()'
  artifacts:
    paths:
      - public
  only:
    - master
