image: r-base

before_script:
  - apt-get update
  - apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev libglu1-mesa-dev libssh2-1-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libgit2-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev pandoc r-cran-devtools r-cran-testthat r-cran-curl r-bioc-biostrings


pages:
  stage: deploy
  script:
    - R -e 'options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/latest"))'
    - R -e 'install.packages("pkgdown")'
    - R -e 'pkgdown::build_site()'
  artifacts:
    paths:
      - public
  only:
    - master
