image: debian:buster-slim

before_script:
  - apt-get update && apt-get -y install pandoc r-base
  - R -e "install.packages('pkgdown',repos='http://cran.rstudio.com')"

pages:
  script:
    - R -e "pkgdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master