image: r-base

pages:
  stage: deploy
  script:
     - R -e 'install.packages(c("dplyr", "purrr", "pkgdown"))'
     - R -e "pkgdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master
